create database company;

use company;

CREATE TABLE WORKER_1
(
 WORKER_ID INT PRIMARY KEY,
 FIRST_NAME VARCHAR(35),
 LAST_NAME VARCHAR(35),
 SALARY INT,
 JOINING_DATE DATE ,
 DEPARTMENT VARCHAR(35)
);

SELECT * FROM WORKER_1;

-- FIRST_NAME ASC
SELECT FIRST_NAME FROM WORKER_1 ORDER BY FIRST_NAME ASC;

-- DEPARTMENT DESC
SELECT DEPARTMENT FROM WORKER_1 ORDER BY DEPARTMENT DESC;

-- TOP 6 RECORD FOR TABLE
SELECT * FROM WORKER_1 LIMIT 6;

SELECT DEPARTMENT FROM WORKER_1 LIMIT 5;





