CREATE DATABASE RAJJ;

USE RAJJ;

CREATE TABLE SCHOO 
(
 ROLL_NO INT PRIMARY KEY,
 FNAME VARCHAR(35),
 LNAME VARCHAR(40),
 ADDRESS VARCHAR(65),
 D_O_B DATE 
);

SELECT * FROM SCHOO;

-- ADD COLUMN 
ALTER TABLE SCHOO
ADD COLUMN NOO INT;

-- PRIMARY KEY AND UNIQUE NUMBER NOT APPLY 
SELECT DISTINCT NOO FROM SCHOO;

-- TABLE COPY 
CREATE TABLE BN SELECT * FROM SCHOO;

CREATE TABLE BR 
(
 ROLL_NO INT PRIMARY KEY,
 FNAME VARCHAR(35),
 LNAME VARCHAR(40),
 ADDRESS VARCHAR(65),
 D_O_B DATE 
);

SELECT * FROM BR;


-- COLUMN NAME CHANGE BUT VALUE NOT CHANGE
INSERT INTO BR (ROLL_NO, FNAME, LNAME, ADDRESS, D_O_B)
SELECT ROLL_NO, FNAME, LNAME, ADDRESS, D_O_B FROM SCHOO;

-- LIMIT FUNCTION USE 
SELECT * FROM BR LIMIT 4;

-- LIKE FUNCTION USE

SELECT * FROM BR WHERE LNAME LIKE "V%";

SELECT * FROM BR WHERE ADDRESS LIKE "M%";

SELECT * FROM BR WHERE ADDRESS LIKE "%V";

SELECT * FROM BR WHERE ADDRESS LIKE "_A%";

SELECT * FROM BR WHERE ADDRESS LIKE "%ST%";

SELECT * FROM BR WHERE ADDRESS LIKE "O%V";


-- this is csv file
select * from csv;






 
