USE RAJJJ;

CREATE TABLE EMPLOYE3
(
 EMPO_ID INT PRIMARY KEY AUTO_INCREMENT,
 F_NAME VARCHAR (35),
 L_NAME VARCHAR (35),
 ADDRESS VARCHAR (65),
 HIRING_DATE DATE,
 SALARY INT,
 DEPARTMENT VARCHAR (10)
);

SELECT * FROM EMPLOYE3; 


-- AND QUERY 

SELECT * from EMPLOYE3 WHERE F_NAME = "PATL" AND L_NAME = "NITIN" ;


-- OR QUERY

SELECT * from EMPLOYE3 WHERE F_NAME = "PATL" OR L_NAME = "PREM" ;


-- NOT QUERY
SELECT * FROM EMPLOYE3 WHERE NOT F_NAME ="RAJPUT";


-- ASCENDING ORDER
SELECT * FROM EMPLOYE3 ORDER BY F_NAME ASC;

-- DESCENDING ORDER
SELECT * FROM EMPLOYE3 ORDER BY L_NAME DESC;

--- INSERT INTO
INSERT INTO EMPLOYE3 VALUES (10,"GUPTA","VAISHALI","VASTRAL","2023-02-12",25000,"SALESMAN");

-- UPDATE QUERY
UPDATE EMPLOYE3 SET F_NAME = "GUPTA" WHERE EMPO_ID = 8;

-- DELETE QUERY FOR ROW DELETE
DELETE FROM EMPLOYE3 WHERE EMPO_ID = 10;


-- If you want to create the same table
CREATE TABLE BRR SELECT * FROM EMPLOYE3;


-- If you want to create the same table but the name of the column should be changed
CREATE TABLE EMPLOYE4
(
 EMPO_ID INT PRIMARY KEY AUTO_INCREMENT,
 F_NAME VARCHAR (35),
 L_NAME VARCHAR (35),
 ADDRESS VARCHAR (65),
 HIRING_DATE DATE,
 SALARY INT,
 DEPARTMENT VARCHAR (10)
);

SELECT * FROM EMPLOYE4; 

INSERT INTO EMPLOYE4 (EMPO_ID, F_NAME, L_NAME, ADDRESS, HIRING_DATE, SALARY, DEPARTMENT) 
SELECT EMPO_ID, F_NAME, L_NAME, AREA, HIRING_DATE, SALARY, DEPARTMENT FROM EMPLOYE3;

-- DELETE ALL RECORD 
DELETE FROM EMPLOYE4;

-- LIMIT QUERY 
SELECT * FROM EMPLOYE4 LIMIT 5;

-- CONDITITON FOR LIMIT QUERY
SELECT * FROM EMPLOYE4 WHERE DEPARTMENT = "SALESMAN" LIMIT 5;

-- MINIMUM QUERY
SELECT MIN(SALARY) FROM EMPLOYE4;

SELECT MIN(SALARY) AS MINIMUM FROM EMPLOYE4;

-- MAXIMUM QUERY
SELECT MAX(SALARY) FROM EMPLOYE4;

SELECT MAX(SALARY) AS MAXIMUM FROM EMPLOYE4;

-- COUNT QUERY
SELECT COUNT(SALARY) FROM EMPLOYE4;

SELECT COUNT(SALARY)AS COUNT FROM EMPLOYE4;



-- SUM QUERY
SELECT SUM(SALARY) FROM EMPLOYE4;

SELECT SUM(SALARY)AS ADDITION FROM EMPLOYE4;

-- AVGERAGE QUERY
SELECT AVG(SALARY) FROM EMPLOYE4;

SELECT AVG(SALARY) AS AVERAGE FROM EMPLOYE4;




-- LIKE QUERY

-- Finds any values that starts with "R"
SELECT * FROM EMPLOYE4 where F_NAME LIKE "R%";

-- Finds any values that ends with "a"
SELECT * FROM EMPLOYE4 where F_NAME LIKE "%A";

-- 	Finds any values that have "HA" in any position
SELECT * FROM EMPLOYE4 where ADDRESS LIKE "%HA%";

-- Finds any values that have "A" in the second position
SELECT * FROM EMPLOYE4 where ADDRESS LIKE "_A%";

-- 	Finds any values that starts with "M" and ends with "R"
SELECT * FROM EMPLOYE4 where ADDRESS LIKE "M%R";






